language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

install:
  - composer install --dev

script:
  - php vendor/bin/codecept build
  - php vendor/bin/codecept clean
  - php vendor/bin/codecept run
